services:
  - type: web
    name: sekolah
    env: php
    buildCommand: |
      apt-get update && apt-get install -y curl gnupg
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      npm install
      npm run prod
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force || true
      php artisan storage:link || true
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
        key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.mcj1ktbhxbbezykjlmnq.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: keluar4bulan
