services:
  - type: web
    name: sekolah
    runtime: php
    envVars:
      - key: DATABASE_URL
        value: ${DATABASE_URL}           # atur di dashboard Render
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
