services:
  - type: web
    name: sekolah
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:HIf1J5DOgzaTPMVgL8cyw8u+5qH/xVmFo9yJXWNWQJ4=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.mcj1ktbhxbbezykjlmnq.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: keluar4bulan
